// Auto-generated by scan.py
// 이 파일을 수동으로 편집하지 마세요

export interface IconItem {
  name: string;
  path: string;
}

export interface IconData {
  [folderPath: string]: IconItem[];
}

export const iconData: IconData = {};